<?php

require_once ('../../../config/databases.php');
require_once ('../../../config/session.php');
require_once ('../../../config/sqlSmart.php');

$dateCom = str_replace("/", "-", $_POST["dateCom"]);
$dateCom = date('d/m/y', strtotime($dateCom));

$dateFim = str_replace("/", "-", $_POST["dateFim"]);
$dateFim = date('d/m/y', strtotime($dateFim));

$dropDev = "DROP TABLE sisrev_comissao";

$con = oci_parse($connBpmgp, $dropDev);
oci_execute($con, OCI_COMMIT_ON_SUCCESS);

$createTableDev = "CREATE TABLE sisrev_comissao (
  
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    XEMPRESA number(3) NULL,
    XREVENDA number(3) NULL,
    XPROPOSTA number(15) NULL,
    XNRONOTA number(15) NULL,
    XTRANSACAO VARCHAR(10) NULL,
    XDTNOTA VARCHAR(10) NULL,
    TIPO_VENDA VARCHAR(12) NULL,
    XCHASSI VARCHAR(80) NULL,
    XCODIGO_VEICULO VARCHAR(15) NULL,
    XVAL_VENDA_VEICULO VARCHAR(13) NULL,
    XVENDEDOR VARCHAR(30) NULL,
    XEMPRESA_VENDEDOR number(10) NULL,
    ID_EMPRESA number(10) NULL,
    XCPF VARCHAR(15) NULL,
    PRIMARY KEY (id))";

$deuBoaCriar = oci_parse($connBpmgp, $createTableDev);
oci_execute($deuBoaCriar, OCI_COMMIT_ON_SUCCESS);


$buscaApollo .= " BETWEEN TO_DATE('".$dateCom."','dd/mm/yy') and 
TO_DATE('".$dateFim."','dd/mm/yy') and 
FMC.TIPO_TRANSACAO IN ('U21','U07','M07','M21','M41','M57','M61') 
ORDER BY 
FNV.EMPRESA,FNV.REVENDA,FNV.NUMERO_NOTA_FISCAL,FNV.SERIE_NOTA_FISCAL,
FNV.CONTADOR,FNV.VENDEDOR";


$resultado = oci_parse($connApollo, $buscaApollo);

oci_execute($resultado, OCI_COMMIT_ON_SUCCESS);

while (($rowInserir = oci_fetch_array($resultado, OCI_ASSOC)) != FAlSE) {
       
    //procurando cpf do Vendedor
    $searchVendedor = "SELECT * FROM FAT_VENDEDOR WHERE VENDEDOR = " . $rowInserir['XVENDEDOR'] . "";

    $achei = oci_parse($connApollo, $searchVendedor);
    oci_execute($achei, OCI_COMMIT_ON_SUCCESS);

    if(($vendedorApollo = oci_fetch_array($achei, OCI_ASSOC)) != FAlSE) 
    { 
        $cpfVendedor = $vendedorApollo['CPF'] ;

        $queryVendedor = "SELECT * FROM VENDEDORES WHERE CPF = " . $cpfVendedor;

        $bpmCon = oci_parse($connBpmgp, $queryVendedor);
        oci_execute($bpmCon, OCI_COMMIT_ON_SUCCESS);

      if (($vendedorBPM = oci_fetch_array($bpmCon, OCI_ASSOC)) != FAlSE) {

        $empresaVendedor = $vendedorBPM['EMPRESA'];

        $nome = $vendedorBPM['NOME'];
        $nome = explode(' ', $nome);
        $nome = $nome[0] . ' ' . $nome[1] . ' ' . $nome[2];
        
      }else {
        $nome = 0;
      }
    }else{
        $nome = 0;
    }

    switch ($rowInserir['XSUBTIPO_TRANSACAO']) {

        case 'T':
            break;
        case 'S':
            break;
        case 'L':
            break;
        case 'A':
            break;
        case 'I':
            break;
        case 'P':
            break;
        case 'Z':
            break;
        case 'D':
            $sqlEmpresa .= " WHERE EMPRESA_APOLLO = ".$rowInserir['XEMPRESA']." AND REVENDA_APOLLO = ".$rowInserir['XREVENDA']." AND SISTEMA NOT IN('N','C','H')";
            
            $result = oci_parse($connBpmgp, $sqlEmpresa);
            oci_execute($result, OCI_COMMIT_ON_SUCCESS);
    
            if($idEmpresaRow = oci_fetch_array($result, OCI_ASSOC))
            {
                $idEmpresa = $idEmpresaRow['ID_EMPRESA'];
            }

            $sqlItensVeiculoDev = "select FMVD.VEICULO as xcodigo_veiculo, 
                        FMVD.NUMERO_NOTA_FISCAL    as xnota_origem_devolucao, 
                        (FMVD.VAL_TOTAL - FMVD.VAL_DESCONTO + FMVD.VAL_ICMS_RETIDO) as xval_venda_veiculo,    
                        VVD.CHASSI as xchassi,   
                        VVD.MODELO as xmodelo,   
                        VMD.DES_MODELO as xdes_modelo,   
                        VPD.PROPOSTA as xproposta,  
                        VVD.ORIGEM_VEICULO as xorigem_veiculo, 
                        VPD.NEGOCIACAO_FINAL as xnegociacao_final   
                        from FAT_MOVIMENTO_CAPA FMCD, FAT_MOVIMENTO_VEICULO FMVD ,VEI_VEICULO VVD ,VEI_MODELO VMD,     
                        VEI_PROPOSTA VPD WHERE 
                        FMCD.EMPRESA = '" . $rowInserir['XEMPRESA'] . "' and 
                        FMCD.REVENDA = '" . $rowInserir['XREVENDA'] . "' and 
                        FMCD.FATOPERACAO = '" . $rowInserir['XFATOPERACAO_ORIGINAL'] . "' and 
                        FMCD.EMPRESA =  FMVD.EMPRESA  and 
                        FMCD.REVENDA = FMVD.REVENDA and 
                        FMCD.NUMERO_NOTA_FISCAL = FMVD.NUMERO_NOTA_FISCAL AND  
                        FMCD.SERIE_NOTA_FISCAL = FMVD.SERIE_NOTA_FISCAL AND  
                        FMCD.CONTADOR = FMVD.CONTADOR AND 
                        FMCD.TIPO_TRANSACAO = FMVD.TIPO_TRANSACAO AND 
                        FMVD.EMPRESA = VVD.EMPRESA and   
                        FMVD.VEICULO = VVD.VEICULO and   
                        VVD.EMPRESA = VMD.EMPRESA and   
                        VVD.MODELO = VMD.MODELO and   
                        FMVD.EMPRESA = VPD.EMPRESA and   
                        FMVD.REVENDA = VPD.REVENDA and 
                        VPD.CONTATO = FMCD.CONTATO";
            //  echo $sqlItensVeiculoDev.'<br>';
            $conexao = oci_parse($connApollo, $sqlItensVeiculoDev);
            oci_execute($conexao, OCI_COMMIT_ON_SUCCESS);
    
            if (($rowDev = oci_fetch_array($conexao, OCI_ASSOC)) != FAlSE) {
    
                $inserirDev = "INSERT INTO sisrev_comissao 
                        (XEMPRESA,XREVENDA,XNRONOTA,XDTNOTA,
                        XTRANSACAO,XVENDEDOR,XEMPRESA_VENDEDOR,XCPF,XCODIGO_VEICULO,
                        XVAL_VENDA_VEICULO,XCHASSI,
                        XPROPOSTA,ID_EMPRESA,TIPO_VENDA)
                        
                            VALUES (
                            " . $rowInserir['XEMPRESA'] . ",
                            " . $rowInserir['XREVENDA'] . ",
                            " . $rowInserir['XNRONOTA'] . ",
                            '" . $rowInserir['XDTNOTA'] . "',
                            '" . $rowInserir['XTRANSACAO'] . "',
                            '" . $nome . "',
                            " . $empresaVendedor . ",
                            '" . $cpfVendedor . "',
                            '" . $rowDev['XCODIGO_VEICULO'] . "',
                            '" .'-'. $rowDev['XVAL_VENDA_VEICULO'] . "',
                            '" . $rowDev['XCHASSI'] . "',
                            " . $rowDev['XPROPOSTA'] . ",
                            " . $idEmpresa . ",
                            'DEVOLUÇÃO'
                            )";
    
                $deuBoa = oci_parse($connBpmgp, $inserirDev);
                oci_execute($deuBoa, OCI_COMMIT_ON_SUCCESS);
            }
            break;
        default:
        $idEmpresaQuery2 = "SELECT ID_EMPRESA FROM EMPRESA WHERE EMPRESA_APOLLO = ".$rowInserir['XEMPRESA']." AND REVENDA_APOLLO = ".$rowInserir['XREVENDA']." AND SISTEMA NOT IN('N','C','H')";
        
        $result2 = oci_parse($connBpmgp, $idEmpresaQuery2);
        oci_execute($result2, OCI_COMMIT_ON_SUCCESS);

        if($idEmpresaRow = oci_fetch_array($result2, OCI_ASSOC)){
            $idEmpresa = $idEmpresaRow['ID_EMPRESA'];
        }
        
        $sqlItensVeiculo =  "select FMV.VEICULO as xcodigo_veiculo,
                    (FMV.VAL_TOTAL - FMV.VAL_DESCONTO + FMV.VAL_ICMS_RETIDO) as xval_venda_veiculo,
                    VV.CHASSI as xchassi,
                    VV.MODELO as xmodelo,
                    VM.DES_MODELO as xdes_modelo,
                    VP.PROPOSTA as xproposta,
                    VV.ORIGEM_VEICULO as xorigem_veiculo,
                    VP.NEGOCIACAO_FINAL as xnegociacao_final
                    from FAT_MOVIMENTO_VEICULO FMV ,VEI_VEICULO VV ,VEI_MODELO VM,
                    VEI_PROPOSTA VP WHERE
                    FMV.EMPRESA = '" . $rowInserir['XEMPRESA'] . "'  and
                    FMV.REVENDA = '" . $rowInserir['XREVENDA'] . "' and
                    FMV.TIPO_TRANSACAO = '" . $rowInserir['XTRANSACAO'] . "' and
                    FMV.NUMERO_NOTA_FISCAL = '" . $rowInserir['XNRONOTA'] . "'  and
                    FMV.SERIE_NOTA_FISCAL = '" . $rowInserir['XSERIENF'] . "' and
                    FMV.CONTADOR = '" . $rowInserir['XCONTADOR_NF'] . "'  and
                    FMV.EMPRESA = VV.EMPRESA and
                    FMV.VEICULO = VV.VEICULO and
                    VV.MODELO = VM.MODELO and
                    VV.EMPRESA = VM.EMPRESA and
                    FMV.EMPRESA = VP.EMPRESA and
                    FMV.REVENDA = VP.REVENDA and
                    VP.CONTATO = '" . $rowInserir['XCONTATO'] . "'";
        
        $success = oci_parse($connApollo, $sqlItensVeiculo);
        oci_execute($success, OCI_COMMIT_ON_SUCCESS);

        if (($rowVeic = oci_fetch_array($success, OCI_ASSOC)) != FAlSE) {

            $inserirDB = "INSERT INTO sisrev_comissao 
                    (XEMPRESA,XREVENDA,XNRONOTA,XDTNOTA,
                    XTRANSACAO,XVENDEDOR,XEMPRESA_VENDEDOR,XCPF,XCODIGO_VEICULO,
                    XVAL_VENDA_VEICULO,XCHASSI,
                    XPROPOSTA,ID_EMPRESA,TIPO_VENDA)
                                    
                    VALUES (
                    " . $rowInserir['XEMPRESA'] . ",
                    " . $rowInserir['XREVENDA'] . ",
                    " . $rowInserir['XNRONOTA'] . ",
                    '" . $rowInserir['XDTNOTA'] . "',
                    '" . $rowInserir['XTRANSACAO'] . "',
                    '" . $nome . "',
                    " . $empresaVendedor . ",
                    '" . $cpfVendedor . "',
                    '" . $rowVeic['XCODIGO_VEICULO'] . "',
                    '" . $rowVeic['XVAL_VENDA_VEICULO'] . "',
                    '" . $rowVeic['XCHASSI'] . "',
                    " . $rowVeic['XPROPOSTA'] . ",
                    ".$idEmpresa.",
                    'VENDA'
                    
                    )";
            $inserirDB = oci_parse($connBpmgp, $inserirDB);
            oci_execute($inserirDB, OCI_COMMIT_ON_SUCCESS);
        }
        break;
    }
   
}

// echo 'Pronto';
header("Location: ./comissaoCanc.php?pg=" . $_GET['pg'] . "&dateCom=" . $dateCom . "&dateFim=" . $dateFim . "");

oci_free_statement($conexao);
oci_free_statement($resultado);
oci_free_statement($execCreate);
oci_free_statement($sucesso);
oci_close($connApollo);
oci_close($connBpmgp);
