<?php

require_once ('../../../config/databases.php');
require_once ('../../../config/session.php');
require_once ('../../../config/sqlSmart.php');

$dateCom = str_replace("/", "-", $_POST["dateCom"]);
$dateCom = date('d/m/y', strtotime($dateCom));

$dateFim = str_replace("/", "-", $_POST["dateFim"]);
$dateFim = date('d/m/y', strtotime($dateFim));

$dropDev = "DROP TABLE sisrev_comissao";

$con = oci_parse($connBpmgp, $dropDev);
oci_execute($con, OCI_COMMIT_ON_SUCCESS);

$createTableDev = "CREATE TABLE sisrev_comissao (
  
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    XEMPRESA number(3) NULL,
    XREVENDA number(3) NULL,
    XPROPOSTA number(15) NULL,
    XNRONOTA number(15) NULL,
    XTRANSACAO VARCHAR(10) NULL,
    XDTNOTA VARCHAR(10) NULL,
    TIPO_VENDA VARCHAR(12) NULL,
    XCHASSI VARCHAR(80) NULL,
    XCODIGO_VEICULO VARCHAR(15) NULL,
    XVAL_VENDA_VEICULO VARCHAR(13) NULL,
    XVENDEDOR VARCHAR(15) NULL,
    ID_EMPRESA number(10) NULL,
    XCPF VARCHAR(15) NULL,
    PRIMARY KEY (id))";

$deuBoaCriar = oci_parse($connBpmgp, $createTableDev);
oci_execute($deuBoaCriar, OCI_COMMIT_ON_SUCCESS);

$criando = "CREATE TABLE sisrev_notas_comissao (
  
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    XEMPRESA number(3) NULL,
    XREVENDA number(3) NULL,
    XPROPOSTA number(15) NULL,
    XNRONOTA number(15) NULL,
    XTRANSACAO VARCHAR(10) NULL,
    XDTNOTA VARCHAR(10) NULL,
    TIPO_VENDA VARCHAR(12) NULL,
    XCHASSI VARCHAR(80) NULL,
    XCODIGO_VEICULO VARCHAR(15) NULL,
    XVAL_VENDA_VEICULO VARCHAR(13) NULL,
    XVENDEDOR VARCHAR(15) NULL,
    ID_EMPRESA number(10) NULL,
    XCPF VARCHAR(15) NULL,
    PRIMARY KEY (id))";

$criou = oci_parse($connBpmgp, $criando);
oci_execute($criou, OCI_COMMIT_ON_SUCCESS);

$buscaApollo .= " BETWEEN TO_DATE('".$dateCom."','dd/mm/yy') and 
TO_DATE('".$dateFim."','dd/mm/yy') and 
FMC.TIPO_TRANSACAO IN ('U21','U07','M07','M21','M41','M57','M61') 
ORDER BY 
FNV.EMPRESA,FNV.REVENDA,FNV.NUMERO_NOTA_FISCAL,FNV.SERIE_NOTA_FISCAL,
FNV.CONTADOR,FNV.VENDEDOR";

$resultado = oci_parse($connApollo, $buscaApollo);

oci_execute($resultado, OCI_COMMIT_ON_SUCCESS);

while (($rowInserir = oci_fetch_array($resultado, OCI_ASSOC)) != FAlSE) {
       
    switch ($rowInserir['XSUBTIPO_TRANSACAO']) {
        case 'T':
            break;
        case 'S':
            break;
        case 'L':
            break;
        case 'A':
            break;
        case 'I':
            break;
        case 'P':
            break;
        case 'Z':
            break;
    }

    $searchVendedor .= " WHERE VENDEDOR = " . $rowInserir['XVENDEDOR'] . "";

    $achei = oci_parse($connApollo, $searchVendedor);
    oci_execute($achei, OCI_COMMIT_ON_SUCCESS);

    while(($vendedorApollo = oci_fetch_array($achei, OCI_ASSOC)) != FAlSE) { 
            $cpfVendedor = $vendedorApollo['CPF'] ;
    }
    
    if ($rowInserir['XSUBTIPO_TRANSACAO'] == 'D') {

        $sqlEmpresa .= " WHERE EMPRESA_APOLLO = ".$rowInserir['XEMPRESA']." AND REVENDA_APOLLO = ".$rowInserir['XREVENDA']." AND SISTEMA NOT IN('N','C','H')";
        
        $result = oci_parse($connBpmgp, $sqlEmpresa);
        oci_execute($result, OCI_COMMIT_ON_SUCCESS);

        if($idEmpresaRow = oci_fetch_array($result, OCI_ASSOC)){
            $idEmpresa = $idEmpresaRow['ID_EMPRESA'];
        }
        $sqlItensVeiculoDev = " WHERE 
                    FMCD.EMPRESA = '" . $rowInserir['XEMPRESA'] . "' and 
                    FMCD.REVENDA = '" . $rowInserir['XREVENDA'] . "' and 
                    FMCD.FATOPERACAO = '" . $rowInserir['XFATOPERACAO_ORIGINAL'] . "' and 
                    FMCD.EMPRESA =  FMVD.EMPRESA  and 
                    FMCD.REVENDA = FMVD.REVENDA and 
                    FMCD.NUMERO_NOTA_FISCAL = FMVD.NUMERO_NOTA_FISCAL AND  
                    FMCD.SERIE_NOTA_FISCAL = FMVD.SERIE_NOTA_FISCAL AND  
                    FMCD.CONTADOR = FMVD.CONTADOR AND 
                    FMCD.TIPO_TRANSACAO = FMVD.TIPO_TRANSACAO AND 
                    FMVD.EMPRESA = VVD.EMPRESA and   
                    FMVD.VEICULO = VVD.VEICULO and   
                    VVD.EMPRESA = VMD.EMPRESA and   
                    VVD.MODELO = VMD.MODELO and   
                    FMVD.EMPRESA = VPD.EMPRESA and   
                    FMVD.REVENDA = VPD.REVENDA and 
                    VPD.CONTATO = FMCD.CONTATO";

        $conexao = oci_parse($connApollo, $sqlItensVeiculoDev);
        oci_execute($conexao, OCI_COMMIT_ON_SUCCESS);

        if (($rowDev = oci_fetch_array($conexao, OCI_ASSOC)) != FAlSE) {

            $inserirDev = "INSERT INTO sisrev_comissao 
                    (XEMPRESA,XREVENDA,XNRONOTA,XDTNOTA,
                    XTRANSACAO,XVENDEDOR,XCPF,XCODIGO_VEICULO,
                    XVAL_VENDA_VEICULO,XCHASSI,
                    XPROPOSTA,ID_EMPRESA,TIPO_VENDA)
                    
                        VALUES (
                        " . $rowInserir['XEMPRESA'] . ",
                        " . $rowInserir['XREVENDA'] . ",
                        " . $rowInserir['XNRONOTA'] . ",
                        '" . $rowInserir['XDTNOTA'] . "',
                        '" . $rowInserir['XTRANSACAO'] . "',
                        " . $rowInserir['XVENDEDOR'] . ",
                        '" . $cpfVendedor . "',
                        '" . $rowDev['XCODIGO_VEICULO'] . "',
                        '" .'-'. $rowDev['XVAL_VENDA_VEICULO'] . "',
                        '" . $rowDev['XCHASSI'] . "',
                        " . $rowDev['XPROPOSTA'] . ",
                        " . $idEmpresa . ",
                        'DEVOLUÇÃO'
                        )";

            $deuBoa = oci_parse($connBpmgp, $inserirDev);
            oci_execute($deuBoa, OCI_COMMIT_ON_SUCCESS);
        }
    } else {

        $idEmpresaQuery2 = "SELECT ID_EMPRESA FROM EMPRESA WHERE EMPRESA_APOLLO = ".$rowInserir['XEMPRESA']." AND REVENDA_APOLLO = ".$rowInserir['XREVENDA']." AND SISTEMA NOT IN('N','C','H')";
        
        $result2 = oci_parse($connBpmgp, $idEmpresaQuery2);
        oci_execute($result2, OCI_COMMIT_ON_SUCCESS);

        if($idEmpresaRow = oci_fetch_array($result2, OCI_ASSOC)){
            $idEmpresa = $idEmpresaRow['ID_EMPRESA'];
        }
        

        $sqlItensVeiculo =  " where
                    FMV.EMPRESA = '" . $rowInserir['XEMPRESA'] . "'  and
                    FMV.REVENDA = '" . $rowInserir['XREVENDA'] . "' and
                    FMV.TIPO_TRANSACAO = '" . $rowInserir['XTRANSACAO'] . "' and
                    FMV.NUMERO_NOTA_FISCAL = '" . $rowInserir['XNRONOTA'] . "'  and
                    FMV.SERIE_NOTA_FISCAL = '" . $rowInserir['XSERIENF'] . "' and
                    FMV.CONTADOR = '" . $rowInserir['XCONTADOR_NF'] . "'  and
                    FMV.EMPRESA = VV.EMPRESA and
                    FMV.VEICULO = VV.VEICULO and
                    VV.MODELO = VM.MODELO and
                    VV.EMPRESA = VM.EMPRESA and
                    FMV.EMPRESA = VP.EMPRESA and
                    FMV.REVENDA = VP.REVENDA and
                    VP.CONTATO = '" . $rowInserir['XCONTATO'] . "'";

        $success = oci_parse($connApollo, $sqlItensVeiculo);
        oci_execute($success, OCI_COMMIT_ON_SUCCESS);

        while (($rowVeic = oci_fetch_array($success, OCI_ASSOC)) != FAlSE) {

            $inserirDB = "INSERT INTO sisrev_comissao 
                    (XEMPRESA,XREVENDA,XNRONOTA,XDTNOTA,
                    XTRANSACAO,XVENDEDOR,XCPF,XCODIGO_VEICULO,
                    XVAL_VENDA_VEICULO,XCHASSI,
                    XPROPOSTA,ID_EMPRESA,TIPO_VENDA)
                                    
                    VALUES (
                    " . $rowInserir['XEMPRESA'] . ",
                    " . $rowInserir['XREVENDA'] . ",
                    " . $rowInserir['XNRONOTA'] . ",
                    '" . $rowInserir['XDTNOTA'] . "',
                    '" . $rowInserir['XTRANSACAO'] . "',
                    " . $rowInserir['XVENDEDOR'] . ",
                    '" . $cpfVendedor . "',
                    '" . $rowVeic['XCODIGO_VEICULO'] . "',
                    '" . $rowVeic['XVAL_VENDA_VEICULO'] . "',
                    '" . $rowVeic['XCHASSI'] . "',
                    " . $rowVeic['XPROPOSTA'] . ",
                    ".$idEmpresa.",
                    'VENDA'
                    
                    )";

            $inserirDB = oci_parse($connBpmgp, $inserirDB);
            oci_execute($inserirDB, OCI_COMMIT_ON_SUCCESS);
        }
    }
}

$empresas = "SELECT NOME_EMPRESA,ID_EMPRESA,EMPRESA_APOLLO,REVENDA_APOLLO FROM EMPRESA WHERE ID_EMPRESA NOT IN (208) ORDER BY ID_EMPRESA ASC";

$sucesso = oci_parse($connBpmgp, $empresas);

oci_execute($sucesso, OCI_COMMIT_ON_SUCCESS);

while (($emp = oci_fetch_array($sucesso, OCI_ASSOC + OCI_RETURN_NULLS)) != FAlSE) {

$vendas = "SELECT * FROM SISREV_COMISSAO order by ID_EMPRESA ASC";

    $conexao2 = oci_parse($connBpmgp, $vendas);
    oci_execute($conexao2, OCI_COMMIT_ON_SUCCESS);

    //while da tabela sisrev_comissao
    while (($dadosComissao = oci_fetch_array($conexao2, OCI_ASSOC)) != FAlSE) {

      $queryVendedor .= " WHERE CPF = " . $dadosComissao['XCPF'];
      $bpmCon = oci_parse($connBpmgp, $queryVendedor);
      oci_execute($bpmCon, OCI_COMMIT_ON_SUCCESS);

      if (($vendedorBPM = oci_fetch_array($bpmCon, OCI_ASSOC)) != FAlSE) {
       

        if ($vendedorBPM['EMPRESA'] == $emp['ID_EMPRESA']) {
            //agora aqui ele separa se a nota fiscal do vendedor é da mesma empresa, se for ele desconsidera
  
            if ($dadosComissao['XEMPRESA'] != $emp['EMPRESA_APOLLO']) {
              //uma query para procurar se o vendedor da tabela sisrev_comissao tem alguma nota cancelada nesse período
              
              $quebrandoCabeça = "INSERT INTO sisrev_notas_comissao 
                    (XEMPRESA,XREVENDA,XNRONOTA,XDTNOTA,
                    XTRANSACAO,XVENDEDOR,XCPF,XCODIGO_VEICULO,
                    XVAL_VENDA_VEICULO,XCHASSI,
                    XPROPOSTA,ID_EMPRESA,TIPO_VENDA)
                                    
                    VALUES (
                    " . $dadosComissao['XEMPRESA'] . ",
                    " . $dadosComissao['XREVENDA'] . ",
                    " . $dadosComissao['XNRONOTA'] . ",
                    '" . $dadosComissao['XDTNOTA'] . "',
                    '" . $dadosComissao['XTRANSACAO'] . "',
                    " . $dadosComissao['XVENDEDOR'] . ",
                    '" . $dadosComissao['XCPF'] . "',
                    '" . $dadosComissao['XCODIGO_VEICULO'] . "',
                    '" . $dadosComissao['XVAL_VENDA_VEICULO'] . "',
                    '" . $dadosComissao['XCHASSI'] . "',
                    " . $dadosComissao['XPROPOSTA'] . ",
                    ".$dadosComissao['ID_EMPRESA'].",
                    '".$dadosComissao['TIPO_VENDA']."'
                    
                    )";

                    $quebrandoCabeça = oci_parse($connBpmgp, $quebrandoCabeça);
                    oci_execute($quebrandoCabeça, OCI_COMMIT_ON_SUCCESS);
            }
          }

      }
    }
}
header("Location: ./comissaoCanc.php?pg=" . $_GET['pg'] . "&dateCom=" . $dateCom . "&dateFim=" . $dateFim . "");

oci_free_statement($conexao);
oci_free_statement($resultado);
oci_free_statement($execCreate);
oci_free_statement($sucesso);
oci_close($connApollo);
oci_close($connBpmgp);
