<?php
require_once ('../../../config/databases.php');
require_once ('../../../config/session.php');
require_once ('../../../config/sqlSmart.php');

$dateCom = $_GET['dateCom'];

$dateFim = $_GET['dateFim'];

$droptable = "DROP TABLE sisrev_comissao_canc";

$conexao = oci_parse($connBpmgp, $droptable);
oci_execute($conexao, OCI_COMMIT_ON_SUCCESS);

$createTableEmp = "CREATE TABLE sisrev_comissao_canc (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    XCODIGO_VEICULO VARCHAR(15) NULL,
    XVAL_VENDA_VEICULO VARCHAR(15) NULL,
    XCHASSI VARCHAR(40) NULL,
    XPROPOSTA NUMBER(10) NULL,
    XEMPRESA NUMBER(5) NULL,
    XREVENDA NUMBER(5) NULL,
    XDTNOTA VARCHAR(80) NULL,
    TIPO_VENDA VARCHAR(12) NULL,
    XTRANSACAO VARCHAR(80) NULL,
    XNRONOTA NUMBER(10) NULL,
    XVENDEDOR NUMBER(10) NULL,
    XCPF VARCHAR(16) NULL,
    ID_EMPRESA number(10) NULL,
    PRIMARY KEY (id))";

$execCreate = oci_parse($connBpmgp, $createTableEmp);

oci_execute($execCreate, OCI_COMMIT_ON_SUCCESS);


$sqlNotasCanc = "SELECT 
    FNV.EMPRESA as xempresa, 
    FNV.REVENDA as xrevenda, 
    FNV.NUMERO_NOTA_FISCAL as xnronota, 
    FNV.SERIE_NOTA_FISCAL as xserienf, 
    FNV.CONTADOR as xcontador_nf,  
    FMC.DTA_ENTRADA_SAIDA as xdtnota, 
    FNV.TIPO_TRANSACAO as xtransacao,  
    FMC.STATUS as xstatus_nf, 
    FC.NOME as xnome_cliente, 
    FTT.SUBTIPO_TRANSACAO as xsubtipo_transacao, 
    FTT.DES_TIPO_TRANSACAO as xdes_tipo_transacao, 
    FTT.UTILIZA_PECAS as xutiliza_pecas, 
    FTT.UTILIZA_OFICINA as xutiliza_oficina, 
    FTT.UTILIZA_VEICULOS as xutiliza_veiculos, 
    FTT.UTILIZA_VEICULOS_NOVOS as xutiliza_veiculos_novos, 
    FMC.CONTATO as xcontato, 
    FNV.VENDEDOR as xvendedor, 
    FMC.FATOPERACAO_ORIGINAL as xfatoperacao_original 
    FROM FAT_NOTAS_VENDEDOR FNV,FAT_MOVIMENTO_CAPA FMC ,  
    FAT_TIPO_TRANSACAO FTT, FAT_CLIENTE FC 
    WHERE  
    FNV.EMPRESA = FMC.EMPRESA and 
    FNV.REVENDA = FMC.REVENDA and 
    FNV.NUMERO_NOTA_FISCAL = FMC.NUMERO_NOTA_FISCAL and 
    FNV.SERIE_NOTA_FISCAL = FMC.SERIE_NOTA_FISCAL and 
    FNV.CONTADOR = FMC.CONTADOR and 
    FNV.TIPO_TRANSACAO = FMC.TIPO_TRANSACAO and 
    FMC.CLIENTE = FC.CLIENTE and 
    FMC.TIPO_TRANSACAO = FTT.TIPO_TRANSACAO and 
    FMC.STATUS IN ('C') and  
    FTT.UTILIZA_VEICULOS = 'S' and 
    FMC.DTA_CANCELAMENTO_NOTA between TO_DATE('$dateCom','dd/mm/yy') and 
    TO_DATE('$dateFim','dd/mm/yy') and 
    FMC.TIPO_TRANSACAO IN ('U21','U07','M07','M21','M41','M57','M61') 
    ORDER BY 
    FNV.EMPRESA,FNV.REVENDA,FNV.NUMERO_NOTA_FISCAL,FNV.SERIE_NOTA_FISCAL,+
    FNV.CONTADOR,FNV.VENDEDOR";

$resultado = oci_parse($connApollo, $sqlNotasCanc);

oci_execute($resultado, OCI_COMMIT_ON_SUCCESS);

while (($row = oci_fetch_array($resultado, OCI_ASSOC + OCI_RETURN_NULLS)) != FAlSE) {

    if ($row['XUTILIZA_VEICULOS_NOVOS'] != 'S') {

        $searchVendedor = "SELECT CPF from FAT_VENDEDOR WHERE VENDEDOR = " . $row['XVENDEDOR'] . "";

        $achei = oci_parse($connApollo, $searchVendedor);
        oci_execute($achei, OCI_COMMIT_ON_SUCCESS);
    
     while(($vendedorApollo = oci_fetch_array($achei, OCI_ASSOC)) != FAlSE) { 
            $xCPF = $vendedorApollo['CPF'] ;
     }
    
        if ($row['XSUBTIPO_TRANSACAO'] == 'D') {

            
            $sqlItensVeiculoCancDevCanc = "select FMVD.VEICULO as xcodigo_veiculo, 
            FMVD.NUMERO_NOTA_FISCAL    as xnota_origem_devolucao, 
            (FMVD.VAL_TOTAL - FMVD.VAL_DESCONTO + FMVD.VAL_ICMS_RETIDO) as xval_venda_veiculo,    
            VVD.CHASSI as xchassi,   
            VVD.MODELO as xmodelo,   
            VMD.DES_MODELO as xdes_modelo,   
            VPD.PROPOSTA as xproposta,  
            VVD.ORIGEM_VEICULO as xorigem_veiculo, 
            VPD.NEGOCIACAO_FINAL as xnegociacao_final   
           from FAT_MOVIMENTO_CAPA FMCD, FAT_MOVIMENTO_VEICULO FMVD ,VEI_VEICULO VVD ,VEI_MODELO VMD,     
           VEI_PROPOSTA VPD where 
           FMCD.EMPRESA =  '" . $row['XEMPRESA'] . "' and 
            FMCD.REVENDA =   '" . $row['XREVENDA'] . "' and 
            FMCD.FATOPERACAO =   '" . $row['XFATOPERACAO_ORIGINAL'] . "' and 
            FMCD.EMPRESA =  FMVD.EMPRESA  and 
            FMCD.REVENDA = FMVD.REVENDA and 
            FMCD.NUMERO_NOTA_FISCAL = FMVD.NUMERO_NOTA_FISCAL AND  
            FMCD.SERIE_NOTA_FISCAL = FMVD.SERIE_NOTA_FISCAL AND  
            FMCD.CONTADOR = FMVD.CONTADOR AND 
            FMCD.TIPO_TRANSACAO = FMVD.TIPO_TRANSACAO AND 
            FMVD.EMPRESA = VVD.EMPRESA and   
            FMVD.VEICULO = VVD.VEICULO and   
            VVD.EMPRESA = VMD.EMPRESA and   
            VVD.MODELO = VMD.MODELO and   
            FMVD.EMPRESA = VPD.EMPRESA and   
            FMVD.REVENDA = VPD.REVENDA and 
            VPD.CONTATO = FMCD.CONTATO";

            $conecta = oci_parse($connApollo, $sqlItensVeiculoCancDevCanc);

            oci_execute($conecta, OCI_COMMIT_ON_SUCCESS);


            while (($achou = oci_fetch_array($conecta, OCI_ASSOC + OCI_RETURN_NULLS)) != FAlSE) {

            $idEmpresaQuery = "SELECT ID_EMPRESA FROM EMPRESA WHERE EMPRESA_APOLLO = ".$row['XEMPRESA']." AND REVENDA_APOLLO = ".$row['XREVENDA']." AND SISTEMA NOT IN('N','C','H')";
        
            $result = oci_parse($connBpmgp, $idEmpresaQuery);
            oci_execute($result, OCI_COMMIT_ON_SUCCESS);
    
            if($idEmpresaRow = oci_fetch_array($result, OCI_ASSOC)){
                $idEmpresa = $idEmpresaRow['ID_EMPRESA'];
            }


                !isset($achou['XCHASSI']) ? $xChassi = '' : $xChassi = $achou['XCHASSI'];
                !isset($achou['XMODELO']) ? $xModelo = '' : $xModelo = $achou['XMODELO'];
                !isset($achou['XPROPOSTA']) ? $xProposta = '0' : $xProposta = $achou['XPROPOSTA'];
                !isset($achou['XCODIGO_VEICULO']) ? $xCodVeiculo = '' : $xCodVeiculo = $achou['XCODIGO_VEICULO'];
                !isset($achou['XVAL_VENDA_VEICULO']) ? $xValVendaVeiculo = '0' : $xValVendaVeiculo = $achou['XVAL_VENDA_VEICULO'];

                $querySmart = "INSERT INTO sisrev_notas_comissao
                    (XEMPRESA,XREVENDA,XNRONOTA,XDTNOTA,XTRANSACAO,
                    XVENDEDOR,TIPO_VENDA,XCODIGO_VEICULO,XVAL_VENDA_VEICULO,XCPF,
                    XCHASSI,XPROPOSTA,ID_EMPRESA
                    )
                
                    VALUES (
                    " . $row['XEMPRESA'] . ",
                    " . $row['XREVENDA'] . ",
                    " . $row['XNRONOTA'] . ",
                    '" . $row['XDTNOTA'] . "',
                    '" . $row['XTRANSACAO'] . "',
                    " . $row['XVENDEDOR'] . ",
                    'CANCELADA',
                    '" . $xCodVeiculo . "',
                    '" . $xValVendaVeiculo . "',
                    '" . $xCPF . "',
                    '" . $xChassi . "',
                    " . $xProposta . ",
                    ".$idEmpresa."
                    
                    )";

                
                $sucesso = oci_parse($connBpmgp, $querySmart);
                oci_execute($sucesso, OCI_COMMIT_ON_SUCCESS);
            }
        } else {
            

            $sqlItensVeiculoCanc =  "select FMV.VEICULO as xcodigo_veiculo,
                      (FMV.VAL_TOTAL - FMV.VAL_DESCONTO + FMV.VAL_ICMS_RETIDO) as xval_venda_veiculo,
                      VV.CHASSI as xchassi,
                      VV.MODELO as xmodelo,
                      VM.DES_MODELO as xdes_modelo,
                      VP.PROPOSTA as xproposta,
                      VV.ORIGEM_VEICULO as xorigem_veiculo,
                      VP.NEGOCIACAO_FINAL as xnegociacao_final
                    from FAT_MOVIMENTO_VEICULO FMV ,VEI_VEICULO VV ,VEI_MODELO VM,
                    VEI_PROPOSTA VP where
                      FMV.EMPRESA = '" . $row['XEMPRESA'] . "'   and
                      FMV.REVENDA =  '" . $row['XREVENDA'] . "' and
                      FMV.TIPO_TRANSACAO =   '" . $row['XTRANSACAO'] . "' and
                      FMV.NUMERO_NOTA_FISCAL =  '" . $row['XNRONOTA'] . "'   and
                      FMV.SERIE_NOTA_FISCAL =   '" . $row['XSERIENF'] . "' and
                      FMV.CONTADOR =  " . $row['XCONTADOR_NF'] . "  and
                      FMV.EMPRESA = VV.EMPRESA and
                      FMV.VEICULO = VV.VEICULO and
                      VV.MODELO = VM.MODELO and
                      VV.EMPRESA = VM.EMPRESA and
                      FMV.EMPRESA = VP.EMPRESA and
                      FMV.REVENDA = VP.REVENDA and
                      VP.CONTATO = '" . $row['XCONTATO'] . "'";
                      
            $veiculoCancCon = oci_parse($connApollo, $sqlItensVeiculoCanc);

            oci_execute($veiculoCancCon, OCI_COMMIT_ON_SUCCESS);

            while (($tipoNaoD = oci_fetch_array($veiculoCancCon, OCI_ASSOC + OCI_RETURN_NULLS)) != FAlSE) {
            $idEmpresaQuery = "SELECT ID_EMPRESA FROM EMPRESA WHERE EMPRESA_APOLLO = ".$row['XEMPRESA']." AND REVENDA_APOLLO = ".$row['XREVENDA']." AND SISTEMA NOT IN('N','C','H')";
        
            $result2 = oci_parse($connBpmgp, $idEmpresaQuery);
            oci_execute($result2, OCI_COMMIT_ON_SUCCESS);
    
            if($idEmpresaRow = oci_fetch_array($result2, OCI_ASSOC)){
                $idEmpresa = $idEmpresaRow['ID_EMPRESA'];
            }

                !isset($tipoNaoD['XCHASSI']) ? $xChassi = '' : $xChassi = $tipoNaoD['XCHASSI'];
                !isset($tipoNaoD['XMODELO']) ? $xModelo = '' : $xModelo = $tipoNaoD['XMODELO'];
                !isset($tipoNaoD['XPROPOSTA']) ? $xProposta = '0' : $xProposta = $tipoNaoD['XPROPOSTA'];
                !isset($tipoNaoD['XCODIGO_VEICULO']) ? $xCodVeiculo = '' : $xCodVeiculo = $tipoNaoD['XCODIGO_VEICULO'];
                !isset($tipoNaoD['XVAL_VENDA_VEICULO']) ? $xValVendaVeiculo = '0' : $xValVendaVeiculo = $tipoNaoD['XVAL_VENDA_VEICULO'];

                $querySmart2 = "INSERT INTO sisrev_notas_comissao
                (XEMPRESA,XREVENDA,XNRONOTA,XDTNOTA,XTRANSACAO,
                XVENDEDOR,TIPO_VENDA,XCODIGO_VEICULO,XVAL_VENDA_VEICULO,XCPF,
                XCHASSI,XPROPOSTA,ID_EMPRESA
                )
                        VALUES (
                    " . $row['XEMPRESA'] . ",
                    " . $row['XREVENDA'] . ",
                    " . $row['XNRONOTA'] . ",
                    '" . $row['XDTNOTA'] . "',
                    '" . $row['XTRANSACAO'] . "',
                    " . $row['XVENDEDOR'] . ",
                    'CANCELADA',
                    '" . $xCodVeiculo . "',
                    '" . $xValVendaVeiculo . "',
                    '" . $xCPF ."',
                    '" . $xChassi . "',
                    " . $xProposta . ",
                    " . $idEmpresa . "
                        )";
                        
                $deuBoa = oci_parse($connBpmgp, $querySmart2);
                oci_execute($deuBoa, OCI_COMMIT_ON_SUCCESS);
            }
        }
    }
}

// $excluiTabela = "DROP TABLE sisrev_notas_nbs";

// $excluir = oci_parse($conn, $excluiTabela);

// oci_execute($excluir, OCI_COMMIT_ON_SUCCESS);

// $createTableNbs = "CREATE TABLE sisrev_notas_nbs (
//     id NUMBER GENERATED BY DEFAULT AS IDENTITY,
//     XCOD_PRODUTO VARCHAR(80) NULL,
//     XCOD_MODELO VARCHAR(80) NULL,
//     XCHASSI VARCHAR(80) NULL,
//     XNOVO_USADO VARCHAR(80) NULL,
//     DATA_FATURAMENTO VARCHAR(80) NULL,
//     NOTA_FABRICA VARCHAR(80) NULL,
//     DATA_NOTA VARCHAR(80) NULL,
//     PLACA_USADO VARCHAR(80) NULL,
//     STATUS VARCHAR(80) NULL,
//     XMODELO VARCHAR(80) NULL,
//     XDES_MODELO VARCHAR(80) NULL,
//     CUSTO_TOTAL_FINAL VARCHAR(80) NULL,
//     DATA_VENDA VARCHAR(80) NULL,
//     GRUPO VARCHAR(80) NULL,
//     COTA VARCHAR(80) NULL,
//     PRIMARY KEY (id))";


// $conNbsBPM = oci_parse($conn, $createTableNbs);

// oci_execute($conNbsBPM, OCI_COMMIT_ON_SUCCESS);

//faz consulta no nbs

// $sqlNotasNbs = "SELECT VENDAS.COD_EMPRESA as xcod_empresa, 
//     (select empresas.cod_matriz from empresas where empresas.cod_empresa = vendas.cod_empresa) as xempresa, 
//     VENDAS.CONTROLE AS xnronota, 
//     VENDAS.COD_PROPOSTA as xproposta, 
//     VENDAS.STATUS as xstatus_nf, 
//     VENDAS.COD_EMPRESA as xrevenda, 
//     VENDAS.SERIE as xserienf, 
//     VENDAS.NUMERO_OS as xordemserv, 
//     VENDAS.VENDEDOR as xvendedor_nbs, 
//     VENDAS.VENDEDOR_ACESSORIO as xvendedor_nbs_agregado, 
//     VENDAS.EMISSAO as xdtnota, 
//     vendas.cod_operacao as xcod_operacao, 
//     VENDAS.TOTAL_NOTA as xtotnfiscal, 
//     (nvl(VENDAS.total_produtos, 0) + 
//     nvl(VENDAS.frete, 0) +     
//     nvl(VENDAS.seguro, 0) +    
//     nvl(VENDAS.outros, 0)) xtotal_produtos, 
//     OPERACOES.OPERACAO as xdes_operacao, 
//     VENDA_STATUS.DESCRICAO as xtipo_venda, 
//     CLIENTE_DIVERSO.NOME  as xnome_cliente, 
//     vendas.ARREDONDAMENTO_PRODUTOS,       
//     vendas.RESPONSAVEL_DESCONTO,          
//     vendas.observacoes,     
//     nvl(vendas.valor_iss,0)  xvaliss, 
//     (nvl(vendas.valor_pis_servico,0) + nvl(vendas.valor_pis_retido,0) + nvl(vendas.valor_pis,0) + nvl(vendas.op_valor_pis,0)) xvalpis,
//     (nvl(vendas.valor_cofins_servico,0) + nvl(vendas.op_valor_cofins,0) + nvl(vendas.valor_cofins,0)) xvalcofins, 
//     vendas.chassi_resumido as xchassi_codigo,  
//     VENDAS_CANCELAMENTO.DATA as xdta_cancelamento 
//     FROM  VENDAS ,
//     VENDA_STATUS,
//     VENDAS_CANCELAMENTO,CLIENTE_DIVERSO, EMPRESAS , operacoes,   
//     empresas_departamentos,venda_controle_entrega x, CLIENTE_DIVERSO arrendatario 
//     WHERE 
//     VENDAS.STATUS                   = VENDA_STATUS.STATUS and   
//     VENDAS.COD_OPERACAO             = OPERACOES.COD_OPERACAO and 
//     VENDAS.COD_empresa              = OPERACOES.COD_empresa and 
//     VENDAS.COD_empresa              = x.COD_empresa(+) and 
//     VENDAS.CONTROLE                 = x.CONTROLE(+) and 
//     VENDAS.SERIE                    = x.SERIE(+) and 
//     vendas.cod_empresa              = empresas.cod_empresa and  
//     VENDAS.COD_CLIENTE              = CLIENTE_DIVERSO.COD_CLIENTE and 
//     VENDAS.cod_cliente_nota         = arrendatario.COD_CLIENTE(+) and 
//     VENDAS.COD_empresa              = empresas_departamentos.COD_empresa and 
//     VENDAS.COD_empresa_departamento = empresas_departamentos.COD_empresa_departamento and 
//     VENDAS.COD_empresa              = VENDAS_CANCELAMENTO.COD_empresa(+) and 
//     VENDAS.controle                 = VENDAS_CANCELAMENTO.controle(+) and 
//     VENDAS.serie                    = VENDAS_CANCELAMENTO.serie(+) and 
//     vendas.status NOT IN ('1')     and 
//     vendas.COD_OPERACAO in (1,2,7,19,26,29,4,9,87,89,28, 3, 78,27) and 
//     TRUNC(VENDAS.EMISSAO) >= '" . $dateCom . "' and 
//     TRUNC(VENDAS.EMISSAO) <= '" . $dateFim . "'";

// $deuBoaNbs = oci_parse($connNbs, $sqlNotasNbs);
// oci_execute($deuBoaNbs, OCI_COMMIT_ON_SUCCESS);

// while (($nbs = oci_fetch_array($deuBoaNbs, OCI_ASSOC + OCI_RETURN_NULLS)) != FAlSE) {

//     $sqlItensVeiculo =  "select V.COD_PRODUTO as xcod_produto,
//         V.COD_MODELO as xcod_modelo, 
//         V.CHASSI_COMPLETO as xchassi, 
//         V.NOVO_USADO as xnovo_usado, 
//         V.DATA_FATURAMENTO,
//         V.NOTA_FABRICA, 
//         V.DATA_NOTA,
//         V.PLACA_USADO,
//         V.STATUS,
//         V.COD_MODELO as xmodelo, 
//         P.DESCRICAO_PRODUTO || PM.DESCRICAO_MODELO as xdes_modelo,
//         V.CUSTO_TOTAL_FINAL,  
//         V.DATA_VENDA,
//         V.GRUPO,
//         V.COTA 
//         from veiculos V ,PRODUTOS_MODELOS PM , 
//         PRODUTOS P where V.chassi_resumido = '" . $nbs['XCHASSI_CODIGO'] . "' AND 
//         PM.COD_PRODUTO = V.Cod_Produto AND 
//         PM.COD_MODELO = V.Cod_Modelo AND  
//         P.COD_PRODUTO = V.COD_PRODUTO and 
//         v.cod_empresa = '" . $nbs['XREVENDA'] . "'";



//     $deuBoa2 = oci_parse($connNbs, $sqlItensVeiculo);
//     oci_execute($deuBoa2, OCI_COMMIT_ON_SUCCESS);

//     while (($nbs2 = oci_fetch_array($deuBoa2, OCI_ASSOC + OCI_RETURN_NULLS)) != FAlSE) {

//         if ($nbs2['XNOVO_USADO'] != 'U') {
//             break;
//         } else {
//             $queryNbs = "INSERT INTO sisrev_notas_nbs 
//             (XCOD_PRODUTO,XCOD_MODELO,XCHASSI,XNOVO_USADO,DATA_FATURAMENTO,NOTA_FABRICA,DATA_NOTA,
//             PLACA_USADO,STATUS,XMODELO,
//             XDES_MODELO,CUSTO_TOTAL_FINAL,DATA_VENDA,GRUPO,COTA)
        
//             VALUES (
//             '" . $nbs2['XCOD_PRODUTO'] . "',
//             '" . $nbs2['XCOD_MODELO'] . "',
//             '" . $nbs2['XCHASSI'] . "',
//             '" . $nbs2['XNOVO_USADO'] . "',
//             '" . $nbs2['DATA_FATURAMENTO'] . "',
//             '" . $nbs2['NOTA_FABRICA'] . "',
//             '" . $nbs2['DATA_NOTA'] . "',
//             '" . $nbs2['PLACA_USADO'] . "',
//             '" . $nbs2['STATUS'] . "',
//             '" . $nbs2['XMODELO'] . "',
//             '" . $nbs2['XDES_MODELO'] . "',
//             '" . $nbs2['CUSTO_TOTAL_FINAL'] . "',
//             '" . $nbs2['DATA_VENDA'] . "',
//             '" . $nbs2['GRUPO'] . "',
//             '" . $nbs2['COTA'] . "')";

//             $deuBoa3 = oci_parse($conn, $queryNbs);
//             oci_execute($deuBoa3, OCI_COMMIT_ON_SUCCESS);
//         }
//     }
// }

 header("Location: ./relatorioSisrev.php?pg=" . $_GET['pg'] . "&dateCom=" . $dateCom . "&dateFim=" . $dateFim . "");


oci_free_statement($conexao);
oci_free_statement($resultado);
oci_free_statement($execCreate);
oci_free_statement($sucesso);
oci_close($connApollo);
oci_close($connBpmgp);
